### ISSUE TITLE
Support 'dotAll' flag ('s')

### ISSUE THREAD

**Issue by avp** [ridiculousfish/regress#1]
The `s` flag allows us to also match line terminators with `.`.

Adding a Node akin to `MatchAnyExceptLineTerminator` called `MatchAny` and allowing it to match line terminators should be relatively straightforward.

**Comment by ridiculousfish** [comment]
Fixed with ebfa3a8067ef9d8e42197479ed26cc3f64483510. Thank you for the awesome and quick PR!
