### ISSUE TITLE
Incorrect Currently Missing Syntax

### ISSUE THREAD

**Issue by RunDevelopment** [ridiculousfish/regress#17]
> Named character classes like `[[:alpha:]]`

ES doesn't support this type of character classes. The only character sets supported are `\d\D\w\W\s\S\p{...}\P{...}` and `.`.

I.e. The regex `/[[:alpha:]]/` is equivalent to `/[\[ahlp:]\]/`.

**Comment by HalidOdat** [comment]
You are right we should remove this :)
