### ISSUE TITLE
The `CodePointSet::inverted()` function is printing things to stdout

### ISSUE THREAD

**Issue by Razican** [ridiculousfish/regress#22]
When running the `CodePointSet::inverted()` function, [this line](https://github.com/ridiculousfish/regress/blob/0762999e28d434c720ddf7acb403e7f920fc9569/src/codepointset.rs#L204) is printing information to stdout, which makes its usage non-silent. This should be avoided.

**Comment by ridiculousfish** [comment]
Yikes! Fixed, thank you!

**Comment by Razican** [comment]
> Yikes! Fixed, thank you!

Thanks for the fix! Would it be possible to release it in crates.io to update our dependency in Boa?

**Comment by ridiculousfish** [comment]
You bet, will do it when I'm off work in a few hours.

**Comment by ridiculousfish** [comment]
[Published as 0.2.0](https://crates.io/crates/regress)

**Comment by Razican** [comment]
> [Published as 0.2.0](https://crates.io/crates/regress)

Thank you for that!
