### ISSUE TITLE
Apache/MIT License

### ISSUE THREAD

**Issue by zbraniecki** [ridiculousfish/regress#3]
Hi!

This crate seems exciting and I can see it bringing great value to the ecosystem. Thank you and congratulations!

A lot of foundational crates in the Rust ecosystem use a dual-license - Apache/MIT. Would you be open to consider extending your license to cover that?
It would help with adoption into all ecosystems that already rely on Apache/MIT.

Thank you!

**Comment by ridiculousfish** [comment]
Yes! Happy to dual license especially if that's the norm in the ecosystem. Thank you for taking the time to write this up!
