### ISSUE TITLE
Bug in named captures

### ISSUE THREAD

**Issue by MrNektom** [ridiculousfish/regress#41]
I'm trying compile this regex `(?<qu>.)` and receive this error `Invalid token at named capture group identifier`.

**Comment by ridiculousfish** [comment]
Yeah looks like `try_consume_named_capture_group_name` is thinks that too much is a Unicode escape, well found.

**Comment by MrNektom** [comment]
This is how he reacts to the "u" symbol, and only if he is not in the first position
