### ISSUE TITLE
Add support for `UTF-16`

### ISSUE THREAD

**Issue by jedel1043** [ridiculousfish/regress#43]
ECMAScript requires that the strings ought to be represented in `UTF-16`, and in Boa we're working on an `UTF-16` based string, but `regress` currently does not expose a way to match on `UTF-16`; understandable since the majority of the Rust ecosystem uses `UTF-8`; or a way to match on arbitrary `[u8]` slices, which is a feature that the `regex` crate does support.

Would it be possible to expose an `UTF-16` API or, alternatively, a raw `[u8]` API?

**Comment by jedel1043** [comment]
Thank you for the quick response!

And don't worry about the required work, I was explicitly asking about its feasibility because I'm planning to contribute that feature to the repo :)

**Comment by raskad** [comment]
Just as an update on this, I got a working version that is almost ready and passes almost all relevant 262 tests.

**Comment by raskad** [comment]
Before I open the PR, I wanted to check in on some open questions / decisions with you @ridiculousfish.

One thing that we have to deal with is of course the UTF-16 byte encoding when we talk about byte matching. I see three distinct cases where we do byte matching at the moment:

1. Matching ASCII chars
2. Matching non-ASCII UTF-8 encoded chars
3. Finding the bytes of a `StartPredicate`

My current assumtion is, that we want to keep the compiled regex portable between different matching methods for now. In the future it may make sense to compile a UTF-8, UTF-16 and ASCII regex differently, but I think that would probably be a major refactor.

Based on that assumtion we have to deal with the above byte encoding cases:

1. Matching ASCII chars should be fine. We just take the next `u16` and check if it is equal to the ASCII byte.
2. I think the most sensible thing would be to remove the UTF-8 encoding byte matches. It makes no sense to decode a UTF-16 unicode char and then encode it in UTF-8 to match the bytes.
3. I think having a byte based `StartPredicate` for UTF-16 regexes makes no sense. As far as I understand, the reason to use a `StartPredicate` is to quickly find the start of a potential match in the input by byte searching. In the UTF-16 case we have to iterate over all `u16`s and compare them to `u8`s. Again this may be okay for ASCII chars but UTF-8 encoded chars have to be de/encoded so the search is probably not efficient.

I think getting really good optimizations will only be possible if we strongly couple the compiled regex type and input type. Until then I would like to work with the current model and disable at least the UTF-8 encoded bytes. I could add a `UTF-16` rust feature and only disable the specific optimizations if the flag is enabled.

**Comment by ridiculousfish** [comment]
That all sounds very reasonable. We don't need the start predicate initially. Having a Rust feature for UTF-16 sounds perfect to me.
