### ISSUE TITLE
Clarification for find_from method

### ISSUE THREAD

**Issue by neeldug** [ridiculousfish/regress#5]
I was wondering whether the [`find_from`](https://github.com/ridiculousfish/regress/blob/d7d5556dc1ceb3bc62e6cb05d00b5ebd0b7a0479/src/api.rs#L208), method uses the start offset as a byte offset as the documentation states or if it is a char offset similar to the Regex crate.

**Comment by BurntSushi** [comment]
The regex crate uses byte offsets, not char offsets.

**Comment by ridiculousfish** [comment]
regress is the same, byte offsets.
