### ISSUE TITLE
non-unicode compliance, part b50b69c9

### ISSUE THREAD

**Issue by selfisekai** [ridiculousfish/regress#53]
youtube strikes again with this new regex:
```js
/(')'("{((),))(,)/
```

error message: `SyntaxError: failed to create matcher: Invalid quantifier`

putting it here so I don't lose it, gonna look into it tomorrow

**Comment by ridiculousfish** [comment]
This is the `{`. In Unicode mode this is a syntax error (incomplete quantifier); in non-Unicode it's a literal {. https://regex101.com is useful for this sort of thing.

**Comment by selfisekai** [comment]
not sure how to touch it from the parser side. it is consumed from the `try_consume_quantifier_prefix` method. I can wrap the errors with `if self.flags.unicode` there, and return `Ok(None)` otherwise, but the chars are already consumed by it, so they don't end up in the match. I can patch up the `{1,2}` quantifier if we're parsing a term, but while the regexes `{`, `{a`, `{1,`, `{1,2`, `{1,2 ` should parse correctly and match all the chars as literal, `{1,2}` should fail parsing. there's no way to "unconsume" a character.

...clone `self.input` to check if next chars are `[{]\d+(?:,\d+)?[}]` and only then proceed with parsing that quantifier?

**Comment by ridiculousfish** [comment]
Time to get very friendly with [ES6 spec Annex B section 1.4](https://262.ecma-international.org/6.0/#sec-regular-expressions-patterns).

The best solution is probably going to be "if you encounter a `{`, then attempt to parse a quantifier; if it fails then treat it as a literal `{` and move on."
