### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by ahlinc** [ridiculousfish/regress#58]
Thank you for the awesome library!

I would like to ask to make a new release that would include the https://github.com/ridiculousfish/regress/commit/cceb877af2e700e9aebc9d7ccbb992fe0332af35 commit and will resolve https://github.com/boa-dev/boa/issues/2638.

**Comment by selfisekai** [comment]
also this one, btw: https://github.com/boa-dev/boa/issues/2325

**Comment by ridiculousfish** [comment]
Released 0.5.0 and published it to crates.io https://crates.io/crates/regress
