### ISSUE TITLE
regress's `find_iter` method

### ISSUE THREAD

**Issue by neeldug** [ridiculousfish/regress#6]
Hi! I was wondering whether when using the `find_iter` method would produce an iterator of matches that only have a singular capture, or whether I'm misunderstanding this. This is just down to the differences between the crates of the `Match` struct in Regex only having a singular match vs regress's captures.

Actually have understood this now, however, with the capture groups and match interaction in regress, does this mean that each match contains many captures, which is similar to how regex's captures method works?

**Comment by ridiculousfish** [comment]
Sorry I missed this question. Yes, `find_iter` produces a sequence of `Match`. A Match is a range of text that matched the regex. If the regex has capture groups, the Match also provides the list of ranges matching that capture group.

Example: the regex `(.)\1` matches two identical characters, and captures the first one. So `find_iter` on the string "aabbcc" will return three Matches, each one containing one capture:

    total: "aa", captures: ["a"]
    total: "bb", captures: ["b"]
    total: "cc", captures: ["c"]

hope that's clear. If there's something that could have been added to the docs to make this clearer I'd be happy to add it!

**Comment by neeldug** [comment]
No worries, and I think it’s probably more on my part rather than the documentation, I’m sorta a novice in regex overall. Thanks, this explanation made a lot of sense to me though!
