### ISSUE TITLE
Request for release (0.7.0 or 0.6.1)

### ISSUE THREAD

**Issue by sirosen** [ridiculousfish/regress#68]
Hi! I recently contributed #67 , and I'm super-happy to see that merged and ready to go.
I was hoping for a release soon so that I can pick this up and incorporate it into my project downstream.
I don't think there's a way for contributors to help with this process.

---

Here's a little sidebar about how I plan to use this crate, in case it's of interest:

I'm the maintainer of [`check-jsonschema`](https://github.com/python-jsonschema/check-jsonschema/), which is a JSON Schema CLI. The JSON Schema spec recommends ECMA regex syntax, and python regex syntax diverges from that slightly.

There's a `regress` python package which wraps this crate (https://github.com/crate-py/regress) made by the `jsonschema` (python package) maintainer. I plan to use `regress` via that package, and plug it in for JSON Schema `"format": "regex"` checking. (The irony of bridging the JS and Python ecosystems via Rust is not lost on me! :grin: )

`check-jsonschema` has a small user community, but this path of `check-jsonschema` -> `regress` (python package) -> `regress` (crate) will help get the package in front of more users. And if we run into issues, I'll be happy to bring whatever fixes I can upstream to this repo!

**Comment by ridiculousfish** [comment]
Published as 0.7.0. Thanks for sharing your use case, I will follow it!
